language: c
sudo: required
dist: trusty
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install cmake -y
  - bash .travis-install-cmocka.sh

script: ./bootstrap && ./configure --with-ssl CFLAGS='-coverage -O0' && make && make check

after_success:
  - rm src/lib/frozen.gc* src/lib/mongoose.gc*
  - bash <(curl -s https://codecov.io/bash) -f '!./amiws_lib.c.gcov' -f '!./test_*' -f '!./src#lib#amipack_parser_*.c.gcov'
